/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteRouteImport } from './routes/$user/route'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as DesignRouteImport } from './routes/design'
import { Route as FaviconDotsvgRouteImport } from './routes/favicon[.]svg'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OgDotpngRouteImport } from './routes/og[.]png'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StatsRouteRouteImport } from './routes/stats/route'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as AuthedInternalRouteRouteImport } from './routes/_authed/internal/route'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as FaviconChar123loginChar125DotsvgRouteImport } from './routes/favicon/{$login}[.]svg'
import { Route as LoginCliRouteImport } from './routes/login_.cli'
import { Route as OgCardIndexRouteImport } from './routes/og-card/index'
import { Route as OgCardLoginRouteImport } from './routes/og-card/$login'
import { Route as OgChar123loginChar125DotpngRouteImport } from './routes/og/{$login}[.]png'

const UserRouteRoute = UserRouteRouteImport.update({
  id: '/$user',
  path: '/$user',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const FaviconDotsvgRoute = FaviconDotsvgRouteImport.update({
  id: '/favicon.svg',
  path: '/favicon.svg',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OgDotpngRoute = OgDotpngRouteImport.update({
  id: '/og.png',
  path: '/og.png',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRouteRoute = StatsRouteRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const homeIndexRoute = homeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedInternalRouteRoute = AuthedInternalRouteRouteImport.update({
  id: '/internal',
  path: '/internal',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const FaviconChar123loginChar125DotsvgRoute =
  FaviconChar123loginChar125DotsvgRouteImport.update({
    id: '/favicon/{$login}.svg',
    path: '/favicon/{$login}.svg',
    getParentRoute: () => rootRouteImport,
  } as any)
const LoginCliRoute = LoginCliRouteImport.update({
  id: '/login_/cli',
  path: '/login/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const OgCardIndexRoute = OgCardIndexRouteImport.update({
  id: '/og-card/',
  path: '/og-card/',
  getParentRoute: () => rootRouteImport,
} as any)
const OgCardLoginRoute = OgCardLoginRouteImport.update({
  id: '/og-card/$login',
  path: '/og-card/$login',
  getParentRoute: () => rootRouteImport,
} as any)
const OgChar123loginChar125DotpngRoute =
  OgChar123loginChar125DotpngRouteImport.update({
    id: '/og/{$login}.png',
    path: '/og/{$login}.png',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/$user': typeof UserRouteRoute
  '/stats': typeof StatsRouteRoute
  '/': typeof homeIndexRoute
  '/design': typeof DesignRoute
  '/favicon.svg': typeof FaviconDotsvgRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/og.png': typeof OgDotpngRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/internal': typeof AuthedInternalRouteRoute
  '/settings': typeof AuthedSettingsRoute
  '/favicon/{$login}.svg': typeof FaviconChar123loginChar125DotsvgRoute
  '/login/cli': typeof LoginCliRoute
  '/og-card/$login': typeof OgCardLoginRoute
  '/og/{$login}.png': typeof OgChar123loginChar125DotpngRoute
  '/og-card/': typeof OgCardIndexRoute
}
export interface FileRoutesByTo {
  '/$user': typeof UserRouteRoute
  '/stats': typeof StatsRouteRoute
  '/': typeof homeIndexRoute
  '/design': typeof DesignRoute
  '/favicon.svg': typeof FaviconDotsvgRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/og.png': typeof OgDotpngRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/internal': typeof AuthedInternalRouteRoute
  '/settings': typeof AuthedSettingsRoute
  '/favicon/{$login}.svg': typeof FaviconChar123loginChar125DotsvgRoute
  '/login/cli': typeof LoginCliRoute
  '/og-card/$login': typeof OgCardLoginRoute
  '/og/{$login}.png': typeof OgChar123loginChar125DotpngRoute
  '/og-card': typeof OgCardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$user': typeof UserRouteRoute
  '/stats': typeof StatsRouteRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/design': typeof DesignRoute
  '/favicon.svg': typeof FaviconDotsvgRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/og.png': typeof OgDotpngRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authed/internal': typeof AuthedInternalRouteRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/favicon/{$login}.svg': typeof FaviconChar123loginChar125DotsvgRoute
  '/login_/cli': typeof LoginCliRoute
  '/og-card/$login': typeof OgCardLoginRoute
  '/og/{$login}.png': typeof OgChar123loginChar125DotpngRoute
  '/(home)/': typeof homeIndexRoute
  '/og-card/': typeof OgCardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$user'
    | '/stats'
    | '/'
    | '/design'
    | '/favicon.svg'
    | '/llms.txt'
    | '/login'
    | '/og.png'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/internal'
    | '/settings'
    | '/favicon/{$login}.svg'
    | '/login/cli'
    | '/og-card/$login'
    | '/og/{$login}.png'
    | '/og-card/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$user'
    | '/stats'
    | '/'
    | '/design'
    | '/favicon.svg'
    | '/llms.txt'
    | '/login'
    | '/og.png'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/internal'
    | '/settings'
    | '/favicon/{$login}.svg'
    | '/login/cli'
    | '/og-card/$login'
    | '/og/{$login}.png'
    | '/og-card'
  id:
    | '__root__'
    | '/$user'
    | '/stats'
    | '/_authed'
    | '/design'
    | '/favicon.svg'
    | '/llms.txt'
    | '/login'
    | '/og.png'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/_authed/internal'
    | '/_authed/settings'
    | '/favicon/{$login}.svg'
    | '/login_/cli'
    | '/og-card/$login'
    | '/og/{$login}.png'
    | '/(home)/'
    | '/og-card/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  UserRouteRoute: typeof UserRouteRoute
  StatsRouteRoute: typeof StatsRouteRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  DesignRoute: typeof DesignRoute
  FaviconDotsvgRoute: typeof FaviconDotsvgRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LoginRoute: typeof LoginRoute
  OgDotpngRoute: typeof OgDotpngRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  FaviconChar123loginChar125DotsvgRoute: typeof FaviconChar123loginChar125DotsvgRoute
  LoginCliRoute: typeof LoginCliRoute
  OgCardLoginRoute: typeof OgCardLoginRoute
  OgChar123loginChar125DotpngRoute: typeof OgChar123loginChar125DotpngRoute
  homeIndexRoute: typeof homeIndexRoute
  OgCardIndexRoute: typeof OgCardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$user': {
      id: '/$user'
      path: '/$user'
      fullPath: '/$user'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favicon.svg': {
      id: '/favicon.svg'
      path: '/favicon.svg'
      fullPath: '/favicon.svg'
      preLoaderRoute: typeof FaviconDotsvgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og.png': {
      id: '/og.png'
      path: '/og.png'
      fullPath: '/og.png'
      preLoaderRoute: typeof OgDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/internal': {
      id: '/_authed/internal'
      path: '/internal'
      fullPath: '/internal'
      preLoaderRoute: typeof AuthedInternalRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/favicon/{$login}.svg': {
      id: '/favicon/{$login}.svg'
      path: '/favicon/{$login}.svg'
      fullPath: '/favicon/{$login}.svg'
      preLoaderRoute: typeof FaviconChar123loginChar125DotsvgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login_/cli': {
      id: '/login_/cli'
      path: '/login/cli'
      fullPath: '/login/cli'
      preLoaderRoute: typeof LoginCliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og-card/': {
      id: '/og-card/'
      path: '/og-card'
      fullPath: '/og-card/'
      preLoaderRoute: typeof OgCardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og-card/$login': {
      id: '/og-card/$login'
      path: '/og-card/$login'
      fullPath: '/og-card/$login'
      preLoaderRoute: typeof OgCardLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/{$login}.png': {
      id: '/og/{$login}.png'
      path: '/og/{$login}.png'
      fullPath: '/og/{$login}.png'
      preLoaderRoute: typeof OgChar123loginChar125DotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedInternalRouteRoute: typeof AuthedInternalRouteRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedInternalRouteRoute: AuthedInternalRouteRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  UserRouteRoute: UserRouteRoute,
  StatsRouteRoute: StatsRouteRoute,
  AuthedRoute: AuthedRouteWithChildren,
  DesignRoute: DesignRoute,
  FaviconDotsvgRoute: FaviconDotsvgRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LoginRoute: LoginRoute,
  OgDotpngRoute: OgDotpngRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  FaviconChar123loginChar125DotsvgRoute: FaviconChar123loginChar125DotsvgRoute,
  LoginCliRoute: LoginCliRoute,
  OgCardLoginRoute: OgCardLoginRoute,
  OgChar123loginChar125DotpngRoute: OgChar123loginChar125DotpngRoute,
  homeIndexRoute: homeIndexRoute,
  OgCardIndexRoute: OgCardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
